In [10]:
import pandas as pd
pd.set_option('display.max_columns',300)
pd.set_option('display.max_rows',300)

In [2]:
bank_df = pd.read_csv('../data/raw/Bank dataset 2.csv')
bank_df.head(10)

,customer_id,age,gender,marital_status,education_level,annual_income,loan_amount,credit_score,employment_years,employment_type,loan_purpose,home_ownership,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,loan_status,application_date,category_feature_1,ratio_feature_2,ratio_feature_3,flag_feature_4,ratio_feature_5,category_feature_6,ratio_feature_7,category_feature_8,category_feature_9,numeric_feature_10,numeric_feature_11,flag_feature_12,ratio_feature_13,numeric_feature_14,category_feature_15,category_feature_16,category_feature_17,numeric_feature_18,ratio_feature_19,ratio_feature_20,ratio_feature_21,numeric_feature_22,flag_feature_23,ratio_feature_24,numeric_feature_25,flag_feature_26,numeric_feature_27,category_feature_28,numeric_feature_29,numeric_feature_30,numeric_feature_31,ratio_feature_32,category_feature_33,flag_feature_34,ratio_feature_35,ratio_feature_36,category_feature_37,category_feature_38,numeric_feature_39,ratio_feature_40,category_feature_41,numeric_feature_42,category_feature_43,category_feature_44,numeric_feature_45,numeric_feature_46,ratio_feature_47,ratio_feature_48,category_feature_49,flag_feature_50,category_feature_51,ratio_feature_52,flag_feature_53,flag_feature_54,ratio_feature_55,ratio_feature_56,flag_feature_57,ratio_feature_58,ratio_feature_59,flag_feature_60,numeric_feature_61,numeric_feature_62,category_feature_63,ratio_feature_64,numeric_feature_65,ratio_feature_66,numeric_feature_67,category_feature_68,flag_feature_69,numeric_feature_70,category_feature_71,category_feature_72,flag_feature_73,flag_feature_74,flag_feature_75,flag_feature_76,category_feature_77,numeric_feature_78,category_feature_79,numeric_feature_80,category_feature_81,ratio_feature_82,flag_feature_83,category_feature_84,numeric_feature_85,category_feature_86,ratio_feature_87,category_feature_88,numeric_feature_89,flag_feature_90,ratio_feature_91,ratio_feature_92,category_feature_93,category_feature_94,category_feature_95,numeric_feature_96,ratio_feature_97,ratio_feature_98,ratio_feature_99,numeric_feature_100,flag_feature_101,numeric_feature_102,flag_feature_103,flag_feature_104,numeric_feature_105,ratio_feature_106,category_feature_107,category_feature_108,ratio_feature_109,numeric_feature_110,flag_feature_111,category_feature_112,category_feature_113,ratio_feature_114,numeric_feature_115,flag_feature_116,category_feature_117,ratio_feature_118,numeric_feature_119,category_feature_120,flag_feature_121,category_feature_122,flag_feature_123,ratio_feature_124,ratio_feature_125,ratio_feature_126,flag_feature_127,category_feature_128,flag_feature_129,category_feature_130,numeric_feature_131,ratio_feature_132,category_feature_133,numeric_feature_134,flag_feature_135,flag_feature_136,category_feature_137,ratio_feature_138,flag_feature_139,ratio_feature_140,category_feature_141,category_feature_142,category_feature_143,numeric_feature_144,ratio_feature_145,numeric_feature_146,category_feature_147,numeric_feature_148,ratio_feature_149,category_feature_150,numeric_feature_151,numeric_feature_152,flag_feature_153,category_feature_154,flag_feature_155,flag_feature_156,ratio_feature_157,ratio_feature_158,category_feature_159,category_feature_160,category_feature_161,category_feature_162,ratio_feature_163,category_feature_164,numeric_feature_165,numeric_feature_166,numeric_feature_167,ratio_feature_168,ratio_feature_169,numeric_feature_170,ratio_feature_171,category_feature_172,category_feature_173,flag_feature_174,flag_feature_175,numeric_feature_176,category_feature_177,ratio_feature_178,category_feature_179,flag_feature_180,flag_feature_181,ratio_feature_182
0,309271753,NaN,Female,Single,High School,22055.04,108494.96,610.0,1.7,NaN,Personal,Own,0.362,NaN,120.0,18.29,Rejected,2018-08-20,A,NaN,0.8574,0.0,0.7336,B,0.5041,A,A,697.34,739.63,0.0,0.4043,1096.49,D,A,A,499.19,0.4712,0.2653,0.8803,633.82,0.0,NaN,964.70,0.0,615.25,C,1069.23,720.63,1129.96,0.5758,C,0.0,0.2669,0.8369,C,B,1056.81,0.8445,A,687.11,C,NaN,707.30,1164.42,0.7887,0.9899,C,1.0,D,0.0661,1.0,0.0,NaN,0.6838,0.0,0.7071,0.6594,0.0,1185.58,1086.64,D,0.1737,866.48,0.0756,NaN,NaN,0.0,1478.68,B,C,1.0,0.0,0.0,1.0,C,789.37,B,550.68,A,0.0744,0.0,B,1289.91,B,0.3189,A,881.89,0.0,0.5750,0.9189,E,A,A,890.54,0.9372,0.0048,0.0611,441.82,NaN,996.11,0.0,0.0,530.58,0.3081,B,NaN,0.3065,1213.61,0.0,A,D,NaN,987.26,0.0,NaN,0.2102,NaN,A,1.0,A,0.0,0.8194,0.0724,0.4315,NaN,A,0.0,C,878.37,0.4568,D,NaN,0.0,0.0,C,0.3466,0.0,0.5222,C,B,B,NaN,0.1254,1242.91,C,991.56,0.6526,E,989.58,515.80,0.0,A,1.0,0.0,0.8856,0.2629,A,C,A,B,0.7634,A,NaN,902.12,1635.40,0.1438,NaN,849.63,0.7481,B,C,0.0,NaN,270.03,C,0.1387,B,1.0,0.0,0.9670
1,311621071,47.0,Male,Single,PhD,17331.80,452629.07,682.0,25.1,Part-time,Business,Mortgage,0.129,2.0,24.0,9.28,Rejected,2019-11-06,A,0.1342,0.1789,0.0,0.7736,B,0.6317,B,B,826.96,NaN,0.0,0.4003,929.92,C,B,A,910.19,0.9826,0.3699,0.2280,577.99,0.0,0.3732,694.83,0.0,398.01,A,NaN,NaN,689.46,0.7106,B,0.0,0.1150,0.6637,A,A,662.64,0.2768,E,1012.13,A,NaN,781.14,864.45,0.4709,0.7926,A,0.0,A,0.3877,0.0,1.0,0.3596,0.1116,0.0,0.2572,0.3269,0.0,1040.29,1043.96,A,NaN,961.40,0.4644,1028.52,NaN,0.0,1118.27,A,B,1.0,0.0,0.0,0.0,B,NaN,NaN,680.23,D,0.7683,0.0,E,374.81,A,0.6027,B,422.14,1.0,0.8593,0.4516,B,C,C,1022.19,0.2115,0.4739,0.5289,1608.64,0.0,931.94,0.0,1.0,935.20,0.2743,D,NaN,NaN,469.86,0.0,A,D,0.8185,961.80,0.0,A,0.9890,NaN,B,0.0,NaN,1.0,0.1201,0.8285,0.6790,0.0,B,1.0,E,NaN,0.8585,A,1149.99,1.0,0.0,A,NaN,NaN,0.6198,B,D,B,1125.27,0.8676,1356.88,A,1228.04,0.5023,A,733.66,1339.63,1.0,NaN,0.0,0.0,0.7027,NaN,B,D,A,A,NaN,C,1050.25,523.38,614.05,0.1478,0.9601,1480.38,0.5400,B,B,0.0,0.0,NaN,C,0.4020,D,0.0,0.0,0.4851
2,267974712,32.0,Male,Single,High School,50765.35,NaN,568.0,9.2,Full-time,Education,Own,0.452,1.0,24.0,7.67,Approved,2015-08-02,B,0.6054,0.9021,NaN,0.9939,A,0.0295,A,E,1486.76,655.86,0.0,0.4772,1238.08,A,NaN,E,NaN,0.1729,0.0565,0.2885,820.39,1.0,0.5597,1262.26,0.0,1189.16,C,1039.41,872.50,846.26,0.6788,E,0.0,0.6404,0.5839,B,B,1041.58,0.4944,A,1479.61,B,A,1429.14,1169.05,0.2588,0.6918,A,0.0,A,NaN,0.0,1.0,0.9161,0.1881,0.0,0.0537,0.2376,0.0,938.46,790.06,D,0.1784,1335.62,0.0687,979.05,A,0.0,635.12,NaN,A,0.0,0.0,1.0,0.0,NaN,1042.31,B,980.64,E,0.1038,0.0,B,1266.71,A,0.3867,A,787.78,0.0,0.7419,0.9618,B,C,A,983.25,0.7929,0.4368,0.6740,936.36,0.0,939.08,NaN,0.0,1161.79,0.8620,C,B,0.1735,1049.69,0.0,C,A,0.3168,1120.41,0.0,A,0.6406,1027.06,NaN,0.0,NaN,1.0,0.6764,NaN,0.3576,0.0,D,0.0,B,NaN,0.4039,A,475.63,NaN,NaN,A,0.8345,0.0,0.8848,A,B,D,1279.89,0.9188,686.07,A,1625.82,0.2882,C,1097.62,995.98,0.0,D,0.0,0.0,0.8357,NaN,E,B,B,B,NaN,C,688.45,1456.15,1133.37,0.5745,0.4258,563.89,0.3754,A,A,0.0,0.0,1267.85,B,0.4022,D,0.0,0.0,0.3559
3,872416260,66.0,Male,NaN,Bachelor,29430.52,314325.91,600.0,37.2,Full-time,Car,Own,0.659,0.0,180.0,5.00,Approved,2023-02-14,A,0.7280,0.3234,0.0,0.1879,B,0.3559,C,E,931.97,1220.79,0.0,0.0964,717.88,E,A,A,430.48,0.4582,0.5284,0.3436,629.52,1.0,0.1667,950.14,1.0,NaN,A,1329.13,1589.69,1049.71,0.4641,A,1.0,0.0009,0.3905,A,A,1026.06,NaN,E,1037.43,D,D,764.19,853.19,0.3321,0.0539,C,1.0,A,0.3294,0.0,0.0,0.7566,0.7426,0.0,0.5481,0.6391,0.0,607.32,965.53,B,0.1538,1049.98,0.6994,635.94,C,1.0,969.34,NaN,A,0.0,0.0,0.0,0.0,A,1005.22,A,933.13,A,NaN,0.0,A,1062.98,A,0.9573,B,1418.56,0.0,0.7788,0.4102,C,A,A,911.83,0.5801,0.4356,0.4070,551.78,0.0,781.70,0.0,1.0,1210.60,0.8538,C,B,0.3679,1049.41,1.0,NaN,B,0.7011,1139.29,0.0,NaN,0.0551,NaN,B,1.0,B,1.0,0.8341,0.7490,0.8988,0.0,A,0.0,A,962.96,0.4131,D,1387.31,NaN,0.0,E,0.1986,0.0,0.1502,A,C,E,576.05,0.9785,1601.62,A,1406.09,0.1370,A,1065.72,1547.09,0.0,D,0.0,1.0,0.2723,0.4698,E,A,D,C,NaN,A,1291.24,849.51,1267.75,0.5813,0.5120,774.57,0.3635,NaN,C,0.0,0.0,874.84,B,0.8048,C,0.0,NaN,0.0481
4,255253104,25.0,Male,Single,Master,9079.24,353758.27,578.0,16.9,Part-time,Personal,Rent,0.405,0.0,60.0,22.69,Approved,2020-06-07,A,0.8568,0.9990,0.0,0.9500,C,0.3664,A,B,776.60,1136.60,0.0,0.4209,1387.66,B,A,A,988.02,0.8010,0.6678,0.3697,700.85,1.0,0.6869,1064.12,1.0,523.32,A,NaN,705.99,1475.64,0.3981,D,1.0,NaN,0.6698,A,C,949.97,0.6185,B,2091.75,A,B,1156.96,695.86,0.1383,0.7137,E,0.0,C,0.8132,1.0,0.0,0.8108,0.0311,0.0,NaN,0.4833,0.0,1159.16,1217.19,A,0.5563,556.64,0.6593,909.69,B,0.0,1439.02,B,C,1.0,0.0,0.0,1.0,A,982.84,E,NaN,A,0.2781,0.0,A,1475.12,B,0.6009,A,983.90,0.0,0.6580,0.1389,A,A,C,771.31,0.8914,0.0935,0.6940,859.95,0.0,1308.85,1.0,0.0,921.58,0.6604,A,A,0.9039,1109.92,0.0,A,A,0.9351,983.09,0.0,D,0.7565,1118.63,NaN,0.0,A,1.0,0.4815,0.4260,0.5626,0.0,C,NaN,A,1591.41,0.2629,NaN,1135.00,1.0,0.0,A,0.9881,1.0,0.0285,D,A,A,1215.28,0.8426,1131.24,D,859.23,0.8271,B,1100.76,375.47,1.0,A,0.0,NaN,0.7544,0.6030,NaN,C,C,A,0.9335,C,971.64,NaN,866.14,0.0306,0.2136,1017.82,0.1860,B,C,0.0,0.0,NaN,A,0.7655,D,0.0,0.0,0.1408
5,192841080,39.0,Male,Married,Bachelor,46310.23,153319.94,693.0,29.4,Full-time,Home,Other,0.048,2.0,120.0,21.79,Approved,2016-02-25,C,0.1691,0.5968,1.0,0.3737,B,0.2927,NaN,D,1059.23,1122.38,0.0,0.1646,NaN,B,A,B,NaN,0.8919,0.0358,0.8198,1181.74,0.0,0.6165,672.59,0.0,NaN,B,1253.13,1350.81,919.32,0.0735,A,0.0,0.2772,0.9161,A,B,906.22,0.1704,A,758.67,B,C,1222.53,998.14,0.8885,0.9283,B,0.0,B,0.9584,0.0,0.0,0.0508,0.1306,0.0,0.4587,0.8439,0.0,1539.85,1193.21,B,0.7803,815.44,0.0249,999.11,A,0.0,1755.78,D,A,NaN,0.0,0.0,0.0,D,833.09,NaN,706.70,E,NaN,1.0,A,827.71,B,0.6555,A,1414.40,1.0,NaN,NaN,A,A,A,1032.49,0.6827,0.3863,0.4440,444.36,0.0,794.22,0.0,0.0,674.76,0.6077,B,E,0.9992,943.00,0.0,B,A,0.8229,936.90,0.0,A,0.4406,897.32,B,1.0,A,0.0,0.4989,0.8736,0.4049,1.0,B,0.0,E,1387.45,0.4468,A,1359.40,NaN,1.0,A,0.2672,NaN,0.4586,A,NaN,D,728.02,0.5518,620.11,B,1029.00,0.1784,A,1244.15,754.18,1.0,B,0.0,0.0,0.7004,0.9189,C,B,NaN,C,0.9813,C,1418.78,1019.16,900.75,0.0268,0.2978,1031.29,0.0612,A,A,0.0,0.0,NaN,B,0.1291,A,0.0,0.0,0.8724
6,965861027,56.0,Male,Married,Bachelor,48332.75,37924.82,717.0,19.4,Full-time,Home,Own,0.029,1.0,36.0,9.91,Approved,2022-11-25,A,0.5481,0.4348,0.0,0.3741,A,0.0838,D,A,843.60,1309.39,0.0,0.4970,309.24,E,A,D,1391.31,NaN,0.5567,0.0174,856.00,0.0,0.6905,974.07,1.0,1270.58,A,964.19,1263.57,769.01,0.3431,D,0.0,0.0469,0.9080,D,D,696.68,0.0804,A,1081.50,D,B,744.87,1142.07,0.0551,0.4890,A,0.0,A,0.6770,1.0,0.0,0.1726,0.4939,0.0,0.6349,0.8614,NaN,1112.54,1031.44,A,0.5794,1300.33,0.7591,787.28,A,0.0,1193.49,B,B,0.0,0.0,0.0,0.0,E,712.22,B,1206.09,C,0.6724,NaN,D,1593.89,A,0.5026,A,1300.13,0.0,0.6633,0.3116,C,D,E,993.89,0.1365,0.6294,NaN,1263.28,0.0,679.67,0.0,0.0,1598.42,0.9260,D,D,0.4206,265.50,0.0,A,A,0.9234,1063.17,0.0,NaN,0.6599,1248.92,E,0.0,NaN,0.0,0.1456,0.3434,0.3431,0.0,B,0.0,B,897.18,0.8971,A,1048.50,0.0,0.0,D,0.5313,0.0,0.9737,B,B,E,856.18,0.9688,514.21,NaN,1089.51,0.2806,B,1202.85,1074.82,1.0,D,0.0,0.0,0.7357,0.6096,A,A,D,B,NaN,B,733.71,1336.68,1010.08,0.4477,0.7576,NaN,0.7897,B,B,0.0,0.0,618.13,A,0.5260,D,0.0,0.0,0.0028
7,984431548,67.0,Male,Single,Bachelor,12383.67,404542.92,742.0,18.6,Full-time,Car,Other,0.783,2.0,360.0,7.37,Rejected,2015-10-13,C,0.1779,0.5074,0.0,0.2583,C,0.3906,A,D,1233.11,1564.16,NaN,0.1191,1570.32,B,A,B,NaN,0.7242,0.7329,0.4860,839.67,0.0,0.7249,1201.70,0.0,967.37,C,1381.57,949.17,941.52,0.4197,C,0.0,0.7437,0.6331,NaN,A,709.18,0.0303,A,1352.24,C,A,NaN,709.21,0.3696,0.7156,A,0.0,B,0.0152,0.0,1.0,0.4047,0.0481,1.0,0.3826,0.0116,0.0,877.10,975.74,B,0.5559,947.99,0.5010,1222.32,C,1.0,1042.63,A,A,1.0,0.0,1.0,0.0,E,1475.66,A,1218.76,E,0.3740,0.0,A,1267.50,C,0.6304,C,1178.19,1.0,0.0780,0.5697,C,A,B,978.57,0.2409,0.5415,0.5399,753.95,0.0,1253.45,0.0,0.0,1437.40,0.6425,A,C,NaN,925.13,1.0,B,B,0.9288,1341.76,1.0,D,0.1668,542.61,E,1.0,B,0.0,0.0609,0.8190,NaN,0.0,B,0.0,A,1177.62,0.1773,E,509.67,0.0,1.0,C,0.4169,1.0,0.5337,C,C,B,1117.13,NaN,922.96,A,NaN,NaN,A,453.08,1538.65,1.0,C,1.0,0.0,0.5584,0.5796,D,D,A,A,NaN,E,1321.61,1167.33,1018.73,0.3442,0.9891,503.65,0.1813,B,B,0.0,0.0,1160.93,B,0.0256,NaN,NaN,0.0,0.1971
8,948999010,65.0,Female,NaN,Diploma,60506.91,349413.17,715.0,2.2,Full-time,Home,Other,0.328,0.0,60.0,NaN,Approved,2023-04-24,B,0.3900,0.1913,0.0,0.3341,A,0.6052,A,A,1374.04,1184.18,1.0,0.3736,1331.48,A,B,A,1045.57,0.8774,0.1176,0.3687,869.79,NaN,0.3993,948.65,0.0,1084.20,A,1357.86,1252.53,787.90,0.6519,A,1.0,0.2828,0.1097,A,E,875.42,NaN,NaN,281.59,A,NaN,NaN,843.88,0.1051,0.4388,NaN,1.0,E,NaN,0.0,NaN,0.4768,0.1194,0.0,0.0415,NaN,0.0,1055.18,269.91,NaN,0.5142,843.17,0.9485,1221.36,C,0.0,890.08,B,C,0.0,0.0,0.0,1.0,C,709.65,B,666.87,C,0.7225,0.0,E,837.28,B,0.5572,A,1415.06,1.0,0.2028,0.9726,A,D,B,1240.82,0.5224,0.4562,0.4331,744.99,1.0,773.74,0.0,1.0,1005.18,0.7006,NaN,B,0.7012,473.05,0.0,A,E,0.9484,1710.52,NaN,B,0.5182,957.73,E,1.0,B,0.0,0.3378,0.0932,0.5665,0.0,C,1.0,C,1316.56,0.1851,D,1276.78,0.0,1.0,D,0.8290,0.0,0.6453,E,C,B,1261.32,0.7469,1183.19,A,758.30,0.3443,NaN,1315.85,1208.53,NaN,A,0.0,0.0,0.4729,0.3806,B,D,A,D,0.3275,C,598.78,1303.88,854.09,0.4664,NaN,1566.75,0.8549,B,NaN,0.0,0.0,830.71,A,0.7160,D,1.0,1.0,0.6642
9,318069503,68.0,Male,Divorced,Bachelor,NaN,177693.14,495.0,NaN,Unemployed,Personal,Rent,0.534,2.0,360.0,18.02,Approved,2015-12-07,B,NaN,0.4247,1.0,0.2679,A,0.2283,C,A,NaN,1082.24,1.0,0.1375,1198.98,D,A,NaN,560.34,0.9849,0.6331,0.5517,NaN,0.0,0.0875,976.32,0.0,1232.73,B,792.43,545.00,743.40,NaN,A,0.0,0.3393,0.2139,B,A,NaN,0.2170,A,1137.88,D,C,922.35,651.50,0.2145,0.5783,A,0.0,A,0.0115,0.0,0.0,0.3500,0.9786,0.0,0.3484,0.8419,1.0,991.82,1447.15,E,0.0521,607.30,0.7348,1566.29,D,0.0,1288.41,D,B,1.0,0.0,NaN,0.0,C,917.92,A,1258.16,A,0.5466,0.0,A,820.29,C,0.3546,C,952.65,0.0,0.2208,0.2889,C,B,C,700.48,0.0621,NaN,0.5165,1234.49,0.0,1527.74,0.0,1.0,888.78,NaN,NaN,B,0.3133,1018.13,0.0,B,A,0.5520,1468.58,1.0,A,0.1001,790.73,A,0.0,B,1.0,0.5303,0.8499,0.5960,0.0,B,NaN,A,1368.92,0.7882,A,1499.99,1.0,1.0,A,0.7349,0.0,0.0810,C,A,A,795.65,NaN,1214.19,E,832.41,0.9821,A,1068.54,590.91,0.0,A,0.0,0.0,0.3046,0.0717,A,D,A,A,0.0962,D,850.37,1349.14,1524.75,0.9522,0.0553,NaN,0.0447,C,A,0.0,0.0,738.98,A,NaN,D,1.0,0.0,0.8124

In [13]:
print(list(bank_df.columns))

['customer_id', 'age', 'gender', 'marital_status', 'education_level', 'annual_income', 'loan_amount', 'credit_score', 'employment_years', 'employment_type', 'loan_purpose', 'home_ownership', 'debt_to_income_ratio', 'existing_loans', 'loan_term_months', 'interest_rate', 'loan_status', 'application_date', 'category_feature_1', 'ratio_feature_2', 'ratio_feature_3', 'flag_feature_4', 'ratio_feature_5', 'category_feature_6', 'ratio_feature_7', 'category_feature_8', 'category_feature_9', 'numeric_feature_10', 'numeric_feature_11', 'flag_feature_12', 'ratio_feature_13', 'numeric_feature_14', 'category_feature_15', 'category_feature_16', 'category_feature_17', 'numeric_feature_18', 'ratio_feature_19', 'ratio_feature_20', 'ratio_feature_21', 'numeric_feature_22', 'flag_feature_23', 'ratio_feature_24', 'numeric_feature_25', 'flag_feature_26', 'numeric_feature_27', 'category_feature_28', 'numeric_feature_29', 'numeric_feature_30', 'numeric_feature_31', 'ratio_feature_32', 'category_feature_33', 'flag_feature_34', 'ratio_feature_35', 'ratio_feature_36', 'category_feature_37', 'category_feature_38', 'numeric_feature_39', 'ratio_feature_40', 'category_feature_41', 'numeric_feature_42', 'category_feature_43', 'category_feature_44', 'numeric_feature_45', 'numeric_feature_46', 'ratio_feature_47', 'ratio_feature_48', 'category_feature_49', 'flag_feature_50', 'category_feature_51', 'ratio_feature_52', 'flag_feature_53', 'flag_feature_54', 'ratio_feature_55', 'ratio_feature_56', 'flag_feature_57', 'ratio_feature_58', 'ratio_feature_59', 'flag_feature_60', 'numeric_feature_61', 'numeric_feature_62', 'category_feature_63', 'ratio_feature_64', 'numeric_feature_65', 'ratio_feature_66', 'numeric_feature_67', 'category_feature_68', 'flag_feature_69', 'numeric_feature_70', 'category_feature_71', 'category_feature_72', 'flag_feature_73', 'flag_feature_74', 'flag_feature_75', 'flag_feature_76', 'category_feature_77', 'numeric_feature_78', 'category_feature_79', 'numeric_feature_80', 'category_feature_81', 'ratio_feature_82', 'flag_feature_83', 'category_feature_84', 'numeric_feature_85', 'category_feature_86', 'ratio_feature_87', 'category_feature_88', 'numeric_feature_89', 'flag_feature_90', 'ratio_feature_91', 'ratio_feature_92', 'category_feature_93', 'category_feature_94', 'category_feature_95', 'numeric_feature_96', 'ratio_feature_97', 'ratio_feature_98', 'ratio_feature_99', 'numeric_feature_100', 'flag_feature_101', 'numeric_feature_102', 'flag_feature_103', 'flag_feature_104', 'numeric_feature_105', 'ratio_feature_106', 'category_feature_107', 'category_feature_108', 'ratio_feature_109', 'numeric_feature_110', 'flag_feature_111', 'category_feature_112', 'category_feature_113', 'ratio_feature_114', 'numeric_feature_115', 'flag_feature_116', 'category_feature_117', 'ratio_feature_118', 'numeric_feature_119', 'category_feature_120', 'flag_feature_121', 'category_feature_122', 'flag_feature_123', 'ratio_feature_124', 'ratio_feature_125', 'ratio_feature_126', 'flag_feature_127', 'category_feature_128', 'flag_feature_129', 'category_feature_130', 'numeric_feature_131', 'ratio_feature_132', 'category_feature_133', 'numeric_feature_134', 'flag_feature_135', 'flag_feature_136', 'category_feature_137', 'ratio_feature_138', 'flag_feature_139', 'ratio_feature_140', 'category_feature_141', 'category_feature_142', 'category_feature_143', 'numeric_feature_144', 'ratio_feature_145', 'numeric_feature_146', 'category_feature_147', 'numeric_feature_148', 'ratio_feature_149', 'category_feature_150', 'numeric_feature_151', 'numeric_feature_152', 'flag_feature_153', 'category_feature_154', 'flag_feature_155', 'flag_feature_156', 'ratio_feature_157', 'ratio_feature_158', 'category_feature_159', 'category_feature_160', 'category_feature_161', 'category_feature_162', 'ratio_feature_163', 'category_feature_164', 'numeric_feature_165', 'numeric_feature_166', 'numeric_feature_167', 'ratio_feature_168', 'ratio_feature_169', 'numeric_feature_170', 'ratio_feature_171', 'category_feature_172', 'category_feature_173', 'flag_feature_174', 'flag_feature_175', 'numeric_feature_176', 'category_feature_177', 'ratio_feature_178', 'category_feature_179', 'flag_feature_180', 'flag_feature_181', 'ratio_feature_182']

In [38]:
column_list = ['customer_id', 'age', 'gender', 'marital_status', 'education_level', 'annual_income', 'loan_amount', 'credit_score', 'employment_years', 'employment_type', 'loan_purpose', 'home_ownership', 'debt_to_income_ratio', 'existing_loans', 'loan_term_months', 'interest_rate', 'loan_status', 'application_date',]
bank_data = bank_df[column_list].copy()
bank_data.head(10)

,customer_id,age,gender,marital_status,education_level,annual_income,loan_amount,credit_score,employment_years,employment_type,loan_purpose,home_ownership,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,loan_status,application_date
0,309271753,NaN,Female,Single,High School,22055.04,108494.96,610.0,1.7,NaN,Personal,Own,0.362,NaN,120.0,18.29,Rejected,2018-08-20
1,311621071,47.0,Male,Single,PhD,17331.80,452629.07,682.0,25.1,Part-time,Business,Mortgage,0.129,2.0,24.0,9.28,Rejected,2019-11-06
2,267974712,32.0,Male,Single,High School,50765.35,NaN,568.0,9.2,Full-time,Education,Own,0.452,1.0,24.0,7.67,Approved,2015-08-02
3,872416260,66.0,Male,NaN,Bachelor,29430.52,314325.91,600.0,37.2,Full-time,Car,Own,0.659,0.0,180.0,5.00,Approved,2023-02-14
4,255253104,25.0,Male,Single,Master,9079.24,353758.27,578.0,16.9,Part-time,Personal,Rent,0.405,0.0,60.0,22.69,Approved,2020-06-07
5,192841080,39.0,Male,Married,Bachelor,46310.23,153319.94,693.0,29.4,Full-time,Home,Other,0.048,2.0,120.0,21.79,Approved,2016-02-25
6,965861027,56.0,Male,Married,Bachelor,48332.75,37924.82,717.0,19.4,Full-time,Home,Own,0.029,1.0,36.0,9.91,Approved,2022-11-25
7,984431548,67.0,Male,Single,Bachelor,12383.67,404542.92,742.0,18.6,Full-time,Car,Other,0.783,2.0,360.0,7.37,Rejected,2015-10-13
8,948999010,65.0,Female,NaN,Diploma,60506.91,349413.17,715.0,2.2,Full-time,Home,Other,0.328,0.0,60.0,NaN,Approved,2023-04-24
9,318069503,68.0,Male,Divorced,Bachelor,NaN,177693.14,495.0,NaN,Unemployed,Personal,Rent,0.534,2.0,360.0,18.02,Approved,2015-12-07

In [19]:
bank_data.isnull().sum()

customer_id                0
age                     3983
gender                  4015
marital_status          4136
education_level         4001
annual_income           3953
loan_amount             4094
credit_score            4009
employment_years        4015
employment_type         3938
loan_purpose            4007
home_ownership          3992
debt_to_income_ratio    3915
existing_loans          3998
loan_term_months        3991
interest_rate           3949
loan_status             4039
application_date        3987
dtype: int64

In [44]:
bank_data.dropna(inplace=True)
bank_data.isnull().sum()
bank_data.reset_index(drop=True, inplace=True)
bank_data.head(10)

,customer_id,age,gender,marital_status,education_level,annual_income,loan_amount,credit_score,employment_years,employment_type,loan_purpose,home_ownership,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,loan_status,application_date
0,311621071,47.0,Male,Single,PhD,17331.80,452629.07,682.0,25.1,Part-time,Business,Mortgage,0.129,2.0,24.0,9.28,Rejected,2019-11-06
1,255253104,25.0,Male,Single,Master,9079.24,353758.27,578.0,16.9,Part-time,Personal,Rent,0.405,0.0,60.0,22.69,Approved,2020-06-07
2,192841080,39.0,Male,Married,Bachelor,46310.23,153319.94,693.0,29.4,Full-time,Home,Other,0.048,2.0,120.0,21.79,Approved,2016-02-25
3,965861027,56.0,Male,Married,Bachelor,48332.75,37924.82,717.0,19.4,Full-time,Home,Own,0.029,1.0,36.0,9.91,Approved,2022-11-25
4,984431548,67.0,Male,Single,Bachelor,12383.67,404542.92,742.0,18.6,Full-time,Car,Other,0.783,2.0,360.0,7.37,Rejected,2015-10-13
5,324506058,32.0,Female,Single,PhD,35348.24,46340.67,743.0,24.2,Self-employed,Home,Own,0.376,1.0,360.0,2.85,Approved,2022-07-01
6,513123400,61.0,Male,Married,Bachelor,69649.42,303174.94,715.0,7.8,Part-time,Business,Mortgage,0.209,1.0,36.0,3.47,Approved,2024-03-24
7,487998143,56.0,Female,Married,Bachelor,45654.19,173705.69,691.0,13.7,Unemployed,Home,Mortgage,0.083,1.0,60.0,15.42,Approved,2022-10-25
8,672263662,57.0,Female,Single,Bachelor,155966.74,12400.56,515.0,32.6,Full-time,Personal,Own,0.323,2.0,24.0,15.98,Approved,2017-05-26
9,139954149,19.0,Male,Single,PhD,50337.98,46225.85,756.0,35.3,Part-time,Business,Rent,0.468,2.0,48.0,18.49,Approved,2015-09-10

In [46]:
bank_data.shape

(12182, 18)

In [43]:
for column in bank_data.columns :
    print(f'....Describing {column}......:')
    print(bank_data[column].describe())
    print('\n')

....Describing customer_id......:
count    1.218200e+04
mean     5.485802e+08
std      2.609694e+08
min      1.001534e+08
25%      3.226295e+08
50%      5.457428e+08
75%      7.739825e+08
max      9.999893e+08
Name: customer_id, dtype: float64


....Describing age......:
count    12182.000000
mean        46.158102
std         16.390476
min         18.000000
25%         32.000000
50%         46.000000
75%         60.000000
max         74.000000
Name: age, dtype: float64


....Describing gender......:
count      12182
unique         3
top       Female
freq        6046
Name: gender, dtype: object


....Describing marital_status......:
count      12182
unique         4
top       Single
freq        5536
Name: marital_status, dtype: object


....Describing education_level......:
count        12182
unique           5
top       Bachelor
freq          4691
Name: education_level, dtype: object


....Describing annual_income......:
count     12182.000000
mean      39222.179174
std       25720.166851
min        2751.030000
25%       22065.170000
50%       32739.780000
75%       48840.817500
max      428919.290000
Name: annual_income, dtype: float64


....Describing loan_amount......:
count     12182.000000
mean     252530.139541
std      142664.829047
min        1019.710000
25%      129793.470000
50%      253589.185000
75%      375652.235000
max      499964.720000
Name: loan_amount, dtype: float64


....Describing credit_score......:
count    12182.000000
mean       679.191348
std         83.158117
min        360.000000
25%        623.000000
50%        680.000000
75%        736.000000
max        850.000000
Name: credit_score, dtype: float64


....Describing employment_years......:
count    12182.000000
mean        19.922213
std         11.549321
min          0.000000
25%          9.700000
50%         19.800000
75%         30.000000
max         40.000000
Name: employment_years, dtype: float64


....Describing employment_type......:
count         12182
unique            4
top       Full-time
freq           6638
Name: employment_type, dtype: object


....Describing loan_purpose......:
count     12182
unique        6
top        Home
freq       3714
Name: loan_purpose, dtype: object


....Describing home_ownership......:
count     12182
unique        4
top         Own
freq       4848
Name: home_ownership, dtype: object


....Describing debt_to_income_ratio......:
count    12182.000000
mean         0.432442
std          0.242038
min          0.010000
25%          0.221000
50%          0.437000
75%          0.641000
max          0.850000
Name: debt_to_income_ratio, dtype: float64


....Describing existing_loans......:
count    12182.000000
mean         1.408800
std          1.189609
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          7.000000
Name: existing_loans, dtype: float64


....Describing loan_term_months......:
count    12182.000000
mean       119.642423
std        112.194242
min         12.000000
25%         36.000000
50%         60.000000
75%        180.000000
max        360.000000
Name: loan_term_months, dtype: float64


....Describing interest_rate......:
count    12182.000000
mean        13.770045
std          6.453578
min          2.510000
25%          8.230000
50%         13.800000
75%         19.360000
max         25.000000
Name: interest_rate, dtype: float64


....Describing loan_status......:
count        12182
unique           2
top       Approved
freq          8710
Name: loan_status, dtype: object


....Describing application_date......:
count          12182
unique          3504
top       2015-02-08
freq              13
Name: application_date, dtype: object

In [66]:
bank_data[['employment_years','age','existing_loans','loan_term_months','credit_score']] = bank_data[['employment_years','age','existing_loans','loan_term_months','credit_score']].astype('int64')
bank_data['application_date'] = pd.to_datetime(bank_data['application_date'])
bank_data.dtypes
bank_data.head(10)

,customer_id,age,gender,marital_status,education_level,annual_income,loan_amount,credit_score,employment_years,employment_type,loan_purpose,home_ownership,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,loan_status,application_date
0,311621071,47,Male,Single,PhD,17331.80,452629.07,682,25,Part-time,Business,Mortgage,0.129,2,24,9.28,Rejected,2019-11-06
1,255253104,25,Male,Single,Master,9079.24,353758.27,578,16,Part-time,Personal,Rent,0.405,0,60,22.69,Approved,2020-06-07
2,192841080,39,Male,Married,Bachelor,46310.23,153319.94,693,29,Full-time,Home,Other,0.048,2,120,21.79,Approved,2016-02-25
3,965861027,56,Male,Married,Bachelor,48332.75,37924.82,717,19,Full-time,Home,Own,0.029,1,36,9.91,Approved,2022-11-25
4,984431548,67,Male,Single,Bachelor,12383.67,404542.92,742,18,Full-time,Car,Other,0.783,2,360,7.37,Rejected,2015-10-13
5,324506058,32,Female,Single,PhD,35348.24,46340.67,743,24,Self-employed,Home,Own,0.376,1,360,2.85,Approved,2022-07-01
6,513123400,61,Male,Married,Bachelor,69649.42,303174.94,715,7,Part-time,Business,Mortgage,0.209,1,36,3.47,Approved,2024-03-24
7,487998143,56,Female,Married,Bachelor,45654.19,173705.69,691,13,Unemployed,Home,Mortgage,0.083,1,60,15.42,Approved,2022-10-25
8,672263662,57,Female,Single,Bachelor,155966.74,12400.56,515,32,Full-time,Personal,Own,0.323,2,24,15.98,Approved,2017-05-26
9,139954149,19,Male,Single,PhD,50337.98,46225.85,756,35,Part-time,Business,Rent,0.468,2,48,18.49,Approved,2015-09-10

In [64]:
bank_data.to_csv('../data/interim/bank_data_cleaned.csv', index=False)