In [1]:
import pandas as pd

In [2]:
Housing_df = pd.read_csv('../data/USA_Housing.csv')
Housing_df.head(10)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
5,80175.754159,4.988408,6.104512,4.04,26748.428425,1.068138e+06,"06039 Jennifer Islands Apt. 443\nTracyport, KS..."
6,64698.463428,6.025336,8.147760,3.41,60828.249085,1.502056e+06,"4759 Daniel Shoals Suite 442\nNguyenburgh, CO ..."
7,78394.339278,6.989780,6.620478,2.42,36516.358972,1.573937e+06,"972 Joyce Viaduct\nLake William, TN 17778-6483"
8,59927.660813,5.362126,6.393121,2.30,29387.396003,7.988695e+05,USS Gilbert\nFPO AA 20957
9,81885.927184,4.423672,8.167688,6.10,40149.965749,1.545155e+06,Unit 9446 Box 0958\nDPO AE 97025

In [3]:
Housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object
dtypes: float64(6), object(1)
memory usage: 273.6+ KB

In [4]:
Housing_df.shape

(5000, 7)

In [5]:
Housing_df.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

In [6]:
Housing_df.isnull().sum()

Avg. Area Income                0
Avg. Area House Age             0
Avg. Area Number of Rooms       0
Avg. Area Number of Bedrooms    0
Area Population                 0
Price                           0
Address                         0
dtype: int64

In [8]:
Housing_df.duplicated().sum()

0

In [9]:
Housing_df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [10]:
for column in Housing_df.columns :
    print(f'....Value_Counts in {column}.....: ')
    print(Housing_df[column].value_counts())
    print('\n')

....Value_Counts in Avg. Area Income.....:
Avg. Area Income
79545.458574    1
68735.436608    1
71635.473101    1
73211.136245    1
86249.993070    1
               ..
66064.532823    1
59390.346824    1
64661.930276    1
73279.030904    1
65510.581804    1
Name: count, Length: 5000, dtype: int64


....Value_Counts in Avg. Area House Age.....:
Avg. Area House Age
5.682861    1
7.721909    1
5.866996    1
6.501139    1
6.155403    1
           ..
6.659562    1
5.664971    1
4.656696    1
5.902296    1
5.992305    1
Name: count, Length: 5000, dtype: int64


....Value_Counts in Avg. Area Number of Rooms.....:
Avg. Area Number of Rooms
7.009188     1
7.621975     1
6.075987     1
10.280022    1
7.967184     1
            ..
6.881398     1
6.750872     1
5.660253     1
8.077578     1
6.792336     1
Name: count, Length: 5000, dtype: int64


....Value_Counts in Avg. Area Number of Bedrooms.....:
Avg. Area Number of Bedrooms
4.38    46
3.17    41
3.40    40
3.16    39
3.22    38
        ..
6.31     7
6.01     6
6.02     6
5.42     6
6.42     5
Name: count, Length: 255, dtype: int64


....Value_Counts in Area Population.....:
Area Population
23086.800503    1
27640.561286    1
43555.460636    1
44198.335811    1
43154.838627    1
               ..
44561.333592    1
28995.964140    1
49457.179373    1
13981.435486    1
46501.283803    1
Name: count, Length: 5000, dtype: int64


....Value_Counts in Price.....:
Price
1.059034e+06    1
1.521141e+06    1
1.148372e+06    1
2.065710e+06    1
1.749820e+06    1
               ..
1.444701e+06    1
7.884278e+05    1
8.759045e+05    1
9.844212e+05    1
1.298950e+06    1
Name: count, Length: 5000, dtype: int64


....Value_Counts in Address.....:
Address
208 Michael Ferry Apt. 674\nLaurabury, NE 37010-5101             1
314 Christopher Square Apt. 404\nLake Ronaldville, SD 42025      1
21042 Wilson Islands Suite 238\nFischerchester, MP 42425-4129    1
Unit 8831 Box 5748\nDPO AE 73012-7314                            1
481 Kaitlin Mission Apt. 309\nJodystad, IA 16947                 1
                                                                ..
054 Carter Crescent Suite 674\nGlennport, WA 11140               1
8460 Kathleen Mission Apt. 482\nPort Amytown, KY 72016           1
3737 Hartman Rue\nReneestad, ID 69250-7718                       1
3465 Latoya Well\nNelsonmouth, MI 55741-4287                     1
37778 George Ridges Apt. 509\nEast Holly, NV 29290-3595          1
Name: count, Length: 5000, dtype: int64

In [11]:
for column in Housing_df.columns :
    print(f'....Describing {column}.....: ')
    print(Housing_df[column].describe())
    print('\n')

....Describing Avg. Area Income.....:
count      5000.000000
mean      68583.108984
std       10657.991214
min       17796.631190
25%       61480.562388
50%       68804.286404
75%       75783.338666
max      107701.748378
Name: Avg. Area Income, dtype: float64


....Describing Avg. Area House Age.....:
count    5000.000000
mean        5.977222
std         0.991456
min         2.644304
25%         5.322283
50%         5.970429
75%         6.650808
max         9.519088
Name: Avg. Area House Age, dtype: float64


....Describing Avg. Area Number of Rooms.....:
count    5000.000000
mean        6.987792
std         1.005833
min         3.236194
25%         6.299250
50%         7.002902
75%         7.665871
max        10.759588
Name: Avg. Area Number of Rooms, dtype: float64


....Describing Avg. Area Number of Bedrooms.....:
count    5000.000000
mean        3.981330
std         1.234137
min         2.000000
25%         3.140000
50%         4.050000
75%         4.490000
max         6.500000
Name: Avg. Area Number of Bedrooms, dtype: float64


....Describing Area Population.....:
count     5000.000000
mean     36163.516039
std       9925.650114
min        172.610686
25%      29403.928702
50%      36199.406689
75%      42861.290769
max      69621.713378
Name: Area Population, dtype: float64


....Describing Price.....:
count    5.000000e+03
mean     1.232073e+06
std      3.531176e+05
min      1.593866e+04
25%      9.975771e+05
50%      1.232669e+06
75%      1.471210e+06
max      2.469066e+06
Name: Price, dtype: float64


....Describing Address.....:
count                                                  5000
unique                                                 5000
top       208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
freq                                                      1
Name: Address, dtype: object